version: "3.9"

services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "127.0.0.1:9080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure:10
    user: root

  mails:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "127.0.0.1:8025:8025" # mailhog's web app (think test instance of gmail)
      # "127.0.0.1:1025:1025" # jenkins will use `mail:1025` to send emails, only map to host if you want to send files


      ## NOTES:
      # Host port bindings are constrained to listening on 127.0.0.1
      # - avoids external access to services
      # - To open external access:
      #   - Remove IP address constraint to open the flood gates
      #   - Bind to another IP 
      # - https://docs.docker.com/config/containers/container-networking/#published-ports
