version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "127.0.0.1:9080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
